BEGIN;
CREATE ROLE FLO;
CREATE SCHEMA DDL01;
CREATE SCHEMA DDL02;
CREATE SCHEMA DDL03;
CREATE SCHEMA DDL04;
CREATE SCHEMA DDL05;
CREATE SCHEMA DDL06;
CREATE TABLE DDL01.debt(
    ort_id SERIAL PRIMARY KEY,
    name VARCHAR(25),
    date_of_creation DATE,
    last_modified TIMESTAMP DEFAULT current_timestamp
);